In [2]:
import numpy as np
from itertools import combinations

## Lexicographic pattern

In [42]:
n_det = 24

n_comb = int((n_det * (n_det - 1) * (n_det - 2)) / 6)
crater_triads = np.empty((n_comb, 3), np.int)
for i, el in enumerate(combinations(np.arange(n_det), 3)):
    crater_triads[i] = el

crater_triads

array([[ 0,  1,  2],
       [ 0,  1,  3],
       [ 0,  1,  4],
       ...,
       [20, 21, 23],
       [20, 22, 23],
       [21, 22, 23]])

## Enhanced Pattern Shifting
Arnas, D., Fialho, M. A. A., & Mortari, D. (2017). Fast and robust kernel generators for star trackers. Acta Astronautica,
134 (August 2016), 291–302. https://doi.org/10.1016/j.actaastro.2017.02.016

In [43]:
def enhanced_pattern_shifting(n):
    for dj in range(1, n-2):
        for dk in range(1, n-dj-1):
            for ii in range(0, 3):
                for i in range(ii, n-dj-dk, 3):
                    j = i + dj
                    k = j + dk
                    yield i, j, k

for it, (i, j, k) in enumerate(enhanced_pattern_shifting(n_det)):
    crater_triads[it] = np.array([i, j, k])
crater_triads

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       ...,
       [20, 21, 23],
       [20, 22, 23],
       [21, 22, 23]])

In [38]:
np.array([i, j, k])[None, :]

array([[1, 4, 5]])